apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-rest-api-deployment
  labels:
    app: django
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      serviceAccountName: "workload-identity-sa"
      containers:
      - name: django
        image: myfirstlab.azurecr.io/djangoapi:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db_name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db_password
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db_port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db_user
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: secret_key
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-keyvault-secrets"
