apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-rest-api-deployment
  labels:
    app: django
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      serviceAccountName: "workload-identity-sa"
      containers:
      - name: django
        image: myfirstlab.azurecr.io/djangoapi:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: awssecret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: awssecret
              key: aws_secret_access_key
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: awssecret
              key: aws_region
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-keyvault-secrets"
