apiVersion: v1
kind: Service
metadata:
  name: django-rest-api
  namespace: drinks-api
  labels:
    app: django
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8000 
